name: env_py311_p5
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
channel_priority: flexible
dependencies:
  - python>=3.10,<3.12
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - h5py
  - imageio
  - pillow
  - opencv
  - tifffile
  - jupyterlab
  - ipykernel
  - notebook
  - ipywidgets
  - sqlalchemy
  - psycopg2
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning
  - torchmetrics
  - scanpy
  - anndata
  - leidenalg
  - igraph
  - accimage
  - intel-ipp
  - libjpeg-turbo
  - timm
  - pip:
      - openpyxl
      - scikit-image
      - numba
      - llvmlite
      - lazy-loader
      - et-xmlfile
      - sklearn-ann
      - torchinfo
      - torchcam
      - captum
      - albumentations
      - monai
      - pydicom
      - grad-cam
      - mlflow